config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("cookbook.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        "forms_ex/",
        include("cookbook.forms_ex.urls", namespace="forms_ex"),
    ),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

cookbook/forms_ex/urls.py
from . import views


app_name = views.app_name
urlpatterns = views.urlpatterns

cookbook/users/urls.py
from django.urls import path

from cookbook.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

cookbook/forms_ex/models.py
from django.db import models

# Create your models here.

cookbook/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

cookbook/forms_ex/forms.py
from crispy_forms import layout
from crispy_forms.helper import FormHelper
from crispy_forms.utils import TEMPLATE_PACK
from django import forms
from django.shortcuts import reverse
from django.template.loader import render_to_string
from django.utils.html import mark_safe


class EmailForm(forms.Form):

    email = forms.EmailField()


class CrispyEmailForm(forms.Form):
    """Form rendered using `{% crispy form %}` tag.

    Using crispy tag allows the form layout (e.g. a Save button) to be delegated to the form.
    """

    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(layout.Submit('submit', 'Save'))


class CrispyAjaxEmailForm(forms.Form):
    """Form rendered using `{% crispy form %}` tag and embedded javascript."""

    email = forms.EmailField()
    media_template = 'forms_ex/snippets/ajax_submission.html'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_action = reverse('forms_ex:ajax_submit')
        self.helper.add_input(layout.Submit('submit', 'Save'))

    @property
    def media(self):
        return mark_safe(render_to_string(self.media_template, {'helper': self.helper}))


class CrispyAjaxModalEmailForm(CrispyAjaxEmailForm):
    """Modal form rendered using `{% crispy form %}` tag and embedded javascript for modal."""

    media_template = 'forms_ex/snippets/modal_ajax_submission.html'


class EmailFormWithBoolean(forms.Form):
    """Form with boolean field must set `required=False` to allow boolean to be unchecked.

    See discussion at https://stackoverflow.com/questions/8542839
    """

    email = forms.EmailField()
    spam_me = forms.BooleanField(required=False)


class CrispyFormWithOnClick(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        # Rather than adding a submit button, add a 
        self.helper.add_input(
            layout.Button(
                name='fire',
                value='Fire',
                onclick="alert('Fired!')",
                css_class='btn btn-primary',
            ),
        )

cookbook/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

cookbook/forms_ex/views.py
from collections import OrderedDict
from textwrap import dedent

from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import path
from django.utils import timezone
from django.views.generic import FormView, TemplateView, View
from mistune import markdown

from . import forms


app_name = 'forms_ex'
urlpatterns = []

_INDEXED_VIEWS = []


def format_desc(desc):
    return markdown(dedent(desc))


def url(url_path, name=None, title=None):
    """Register view under the given url path."""
    if name is None:
        name = url_path.replace('/', '_')

    def decorator(view_class):
        urlpatterns.append(path(url_path, view_class.as_view(), name=name))
        if title is not None:
            view_name = f'{app_name}:{name}'
            _INDEXED_VIEWS.append((view_name, title))
        return view_class

    return decorator


class ConfirmAndRedirectToSelfMixin(SuccessMessageMixin):
    """View mixin to redirect form submission to the same page and confirm submission."""

    success_message = 'Form submission successful!'
    success_url = '/'  # Placeholder overriden by return value of `form_valid`.

    def form_valid(self, form):
        super().form_valid(form)
        return redirect(self.request.path_info)


@url('', name='index')
class IndexView(TemplateView):

    template_name = 'forms_ex/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        view_names_and_titles = _INDEXED_VIEWS
        # Update titles with markdown parser.
        view_names_and_titles = [(view_name, markdown(title))
                                 for view_name, title in view_names_and_titles]
        context['view_names_and_titles'] = view_names_and_titles

        return context


@url('email_form', title='Basic form (`{{ form.as_p }}`)')
class EmailFormView(ConfirmAndRedirectToSelfMixin, FormView):

    description = format_desc("""
        Basic email form formatted using `{{ form.as_p }}`
    """)

    template_name = 'forms_ex/email_form.html'
    form_class = forms.EmailForm


@url('email_form_as_ul', title='Basic form (`{{ form.as_ul }}`)')
class EmailFormAsULView(ConfirmAndRedirectToSelfMixin, FormView):

    description = format_desc("""
        Basic email form formatted using `{{ form.as_ul }}`
    """)

    template_name = 'forms_ex/email_form_as_ul.html'
    form_class = forms.EmailForm


@url('email_form_as_table', title='Basic form (`{{ form.as_table }}`)')
class EmailFormAsTableView(ConfirmAndRedirectToSelfMixin, FormView):

    description = format_desc("""
        Basic email form formatted using `{{ form.as_table }}`
    """)
    template_name = 'forms_ex/email_form_as_table.html'
    form_class = forms.EmailForm


@url('email_form_crispy_filter', title='Basic form (`{{ form|crispy }}`)')
class EmailFormCrispyFilterView(ConfirmAndRedirectToSelfMixin, FormView):

    description = format_desc("""
        Basic email form formatted using `{{ form|crispy }}`. With the `crispy` filter, the layout
        is similar to `form.as_*`, except that the layout is done using bootstrap.
    """)

    template_name = 'forms_ex/email_form_crispy_filter.html'
    form_class = forms.EmailForm


@url('email_form_crispy_tag', title='Basic form (`{% crispy form %}`)')
class EmailFormCrispyTagView(ConfirmAndRedirectToSelfMixin, FormView):

    description = format_desc("""
        Basic email form formatted using `{% crispy form %}`. In addition to the styling provided
        by the `crispy` filter, the `crispy` tag also adds the `csrf_token` and allows additional
        layout using code added to the `Form` model.
    """)

    template_name = 'forms_ex/email_form_crispy_tag.html'
    form_class = forms.CrispyEmailForm


@url('email_form_with_ajax_media', title='Email form with ajax media')
class EmailFormWithAjaxMediaView(FormView):

    template_name = 'forms_ex/email_form_crispy_tag.html'
    form_class = forms.CrispyAjaxEmailForm


@url('email_modal', title='Modal form')
class EmailModalView(ConfirmAndRedirectToSelfMixin, FormView):

    template_name = 'forms_ex/email_modal.html'
    form_class = forms.CrispyEmailForm


@url('email_modal_with_ajax_snippet', title='Modal form with ajax snippet')
class EmailModalWithAjaxSnippetView(FormView):

    template_name = 'forms_ex/email_modal_with_ajax_snippet.html'
    form_class = forms.CrispyEmailForm


@url('email_modal_with_ajax_media', title='Modal form with ajax media')
class EmailModalWithAjaxMediaView(FormView):

    template_name = 'forms_ex/email_modal.html'
    form_class = forms.CrispyAjaxModalEmailForm


@url('email_form_with_boolean', title='Basic form with boolean')
class EmailFormWithBooleanView(ConfirmAndRedirectToSelfMixin, FormView):

    template_name = 'forms_ex/email_form_crispy_filter.html'
    form_class = forms.EmailFormWithBoolean


@url('crispy_form_with_onclick', title='Crispy form with onclick handler')
class CrispyFormWithOnClickView(FormView):

    template_name = 'forms_ex/email_form_crispy_tag.html'
    form_class = forms.CrispyFormWithOnClick


@url('ajax_submit')
class AjaxSubmitView(View):

    def post(self, request, *args, **kwargs):
        msg = "Successfully submitted at {:%X}".format(timezone.now())
        return JsonResponse({'success_msg': msg})

cookbook/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

cookbook/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

cookbook/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %}django-cookbook{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <![endif]-->

        <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

        {% block css %}

            <!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">


            <!-- Your stuff: Third-party CSS libraries go here -->

            <!-- This file stores project-specific CSS -->

            <link href="{% static 'css/project.css' %}" rel="stylesheet">


        {% endblock %}

    </head>

    <body>

        <div class="m-b-1">
            <nav class="navbar navbar-expand-md navbar-light bg-light">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">django-cookbook</a>

                {% with app_name=request.resolver_match.app_name %}
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item {% if not app_name %}active{% endif %}">
                                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item {% if app_name == 'forms_ex' %}active{% endif %}">
                                <a class="nav-link" href="{% url 'forms_ex:index' %}">Forms</a>
                            </li>
                        </ul>
                    </div>
                {% endwith %}
            </nav>

        </div>

        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
                {% endfor %}
            {% endif %}
            <div id="js-notification" class="alert" style="display:none;"></div>

            <div class="mt-5">
                {% block content %}
                    <p>Use this document as a way to quick start any new project.</p>
                {% endblock content %}
            </div>

        </div> <!-- /container -->

        {% block modal %}{% endblock modal %}

        <!-- Le javascript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            {% block javascript %}

                <!-- Required by Bootstrap v4.1.1 -->
                <script
                  src="https://code.jquery.com/jquery-3.3.1.min.js"
                  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                  crossorigin="anonymous"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

                <!-- Your stuff: Third-party javascript libraries go here -->


                <!-- place project specific Javascript in this file -->

                <script src="{% static 'js/project.js' %}"></script>
            {% endblock javascript %}
    </body>
</html>

cookbook/templates/base_example.html
{% extends "base.html" %}

{% block content %}
    <div class="card">
        <div class="card-body">
            {% block example %}
            {% endblock example %}
        </div>
    </div>
    </div>

    {% if view.description %}
        <div class="mt-5">
            {{ view.description|safe }}
        </div>
    {% endif %}

{% endblock content %}